version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/myDatabase
    depends_on:
      - mongo
    volumes:
      - .:/app
    networks:
      - flask-mongo-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - flask-mongo-network

volumes:
  mongo-data:

networks:
  flask-mongo-network:
